spring:
  application:
    name: Telco-Incident-Management
  datasource:
    url: jdbc:postgresql://localhost:5432/telco_incident_db
    username: postgres
    password: aArkus14

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  observability:
    logstash:
      host: localhost
      port: 5000
